name: Build and Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Build & Publish Electron App (Windows)
        if: matrix.os == 'windows-latest'
        run: npx electron-builder --win -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Electron App (Mac)
        if: matrix.os == 'macos-latest'
        run: npx electron-builder --mac -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
